CREATE TABLE customer_order
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT         NOT NULL,   -- stable id from the token's subject
    username     VARCHAR(50)    NOT NULL,   -- snapshot for display; identity is user_id
    product_id   BIGINT         NOT NULL, -- NOT a foreign key: that table lives in another service
    product_name VARCHAR(255)   NOT NULL, -- snapshot
    unit_price   NUMERIC(38, 2) NOT NULL, -- snapshot: price at purchase time, never a live lookup
    quantity     INT            NOT NULL,
    status       VARCHAR(20)    NOT NULL,
    created_at   TIMESTAMPTZ    NOT NULL,
    returned_at  TIMESTAMPTZ,             -- null until returned

    CONSTRAINT order_quantity_positive CHECK (quantity > 0),
    CONSTRAINT order_price_positive CHECK (unit_price > 0)
);

CREATE INDEX idx_order_user_id ON customer_order (user_id);