-- An order holds many lines now, so the product columns move into their own table.
-- V1 is already applied, so this is a follow-up migration rather than an edit:
-- Flyway checksums applied migrations and refuses to start if one changed.

ALTER TABLE customer_order DROP CONSTRAINT order_quantity_positive;
ALTER TABLE customer_order DROP CONSTRAINT order_price_positive;

ALTER TABLE customer_order DROP COLUMN product_id;
ALTER TABLE customer_order DROP COLUMN product_name;
ALTER TABLE customer_order DROP COLUMN unit_price;
ALTER TABLE customer_order DROP COLUMN quantity;

CREATE TABLE order_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- This foreign key IS allowed: both tables belong to order-service. The one we
    -- could not create is product_id, because that table lives in another service.
    order_id     BIGINT         NOT NULL REFERENCES customer_order (id) ON DELETE CASCADE,

    product_id   BIGINT         NOT NULL,
    product_name VARCHAR(255)   NOT NULL,   -- snapshot
    unit_price   NUMERIC(38, 2) NOT NULL,   -- snapshot: price at purchase time
    quantity     INT            NOT NULL,

    CONSTRAINT order_item_quantity_positive CHECK (quantity > 0),
    CONSTRAINT order_item_price_positive    CHECK (unit_price > 0)
);

CREATE INDEX idx_order_item_order_id ON order_item (order_id);
