-- 1) The new table. A category is defined once here, instead of being repeated
--    as a string on every product row.
CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    -- UNIQUE teaches the DB the "one row per category name" rule. It also creates
    -- an index as a side effect, so looking a category up by name stays fast.
    CONSTRAINT category_name_unique UNIQUE (name)
);

-- 2) Seed rows. Reference data (a small fixed list the app depends on) belongs in a
--    migration. Test fixtures do NOT - those belong in test setup.
INSERT INTO category (name) VALUES ('Uncategorized'), ('Electronics'), ('Accessories');

-- 3) Adding a REQUIRED foreign key to a table that already holds rows cannot be done
--    in a single statement: the existing rows have no value to put there yet.
--    The standard three-step move is add-nullable -> backfill -> tighten.
ALTER TABLE product ADD COLUMN category_id BIGINT;

UPDATE product
SET category_id = (SELECT id FROM category WHERE name = 'Uncategorized')
WHERE category_id IS NULL;   -- park every pre-existing product in the fallback category

ALTER TABLE product ALTER COLUMN category_id SET NOT NULL;

-- 4) The foreign key constraint itself. From now on the DB refuses a product that
--    points at a non-existent category id, and refuses deleting a category still in use.
ALTER TABLE product
    ADD CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category (id);

-- 5) Postgres does NOT index a foreign key automatically (MySQL/InnoDB does).
--    Without this index, "all products in category X" scans the entire product table.
CREATE INDEX idx_product_category_id ON product (category_id);
