-- "user" is a reserved word in Postgres, hence app_user.
CREATE TABLE app_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50)  NOT NULL,
    password VARCHAR(100) NOT NULL, -- BCrypt hash (always 60 chars); never plaintext
    enabled  BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT app_user_username_unique UNIQUE (username)
);

-- One row per (user, role). This is exactly the shape @ElementCollection maps to:
-- values owned by a user, with no identity of their own.
CREATE TABLE user_role
(
    user_id BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    role    VARCHAR(30) NOT NULL,
    PRIMARY KEY (user_id, role) -- the same role cannot be granted twice
);
-- ON DELETE CASCADE: deleting a user removes their role rows, so no orphans are left behind